permalink: /:title
description: Songs from an eclectic galaxy.

media: "/assets/images/"

linkopener: 'target="_blank" rel="noopener noreferrer"'

collections:
  heists:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

exclude: ["/assets/images/not-in-use","spacethief.code-workspace"]
